/**
 * Instruction Builder
 *
 * Assembles the final Copilot instruction pack from agent outputs and
 * writes it to `.github/copilot-instructions.md` in the target repo.
 */

import fs from "fs";
import path from "path";

/**
 * Write the generated instructions to the target repository.
 *
 * @param {object} params
 * @param {string} params.repoPath    - Absolute path to the target repo
 * @param {string} params.instructions - Markdown content to write
 * @returns {string} The path of the written file
 */
export function writeInstructionPack({ repoPath, instructions }) {
  const outputDir = path.join(repoPath, ".github");
  const outputFile = path.join(outputDir, "copilot-instructions.md");

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputFile, instructions, "utf8");
  console.log(`📝 Instruction pack written to: ${outputFile}`);
  return outputFile;
}

/**
 * Render a structured instruction pack from its components.
 *
 * @param {object} params
 * @param {string} params.profileRules
 * @param {string} params.profileVersion
 * @param {string} params.repo
 * @param {string} params.language
 * @param {string} params.framework
 * @param {string[]} params.dependencies
 * @returns {string} Full Markdown string
 */
export function renderInstructionPack({
  profileRules,
  profileVersion,
  repo,
  language,
  framework,
  dependencies,
}) {
  return `# GitHub Copilot Instructions
<!-- Auto-generated by AI Copilot Instruction Factory -->
<!-- Profile: AI-FACTORY-${profileVersion} -->

## Agent Profile

${profileRules}

---

## Project Context

| Field | Value |
|-------|-------|
| Repository | \`${repo}\` |
| Language | ${language} |
| Framework | ${framework} |
| Key dependencies | ${dependencies.length > 0 ? dependencies.join(", ") : "none"} |

---

## Coding Standards

- Follow **modular architecture** — one clear responsibility per module
- **No hardcoded secrets** — use \`process.env.*\` references or a secrets manager
- Use the **shared Supabase client** (\`supabase/client.js\`) exclusively
- All async functions must handle errors explicitly (no silent catches)
- Prefer **named exports** over default exports for better tree-shaking
- Write self-documenting code; add JSDoc only where behaviour is non-obvious

---

## Architecture Constraints

- Entry point flows: \`launcher/launcher.py\` → \`core/workflow-engine.js\`
- Agent pipeline **must** be coordinated by the Orchestrator Agent
- All Supabase reads/writes go through \`supabase/client.js\`
- Shared utilities live in \`shared/\` — never duplicate logic across modules
- Edge functions are deployed via \`scripts/deploy_functions.ps1\`

---

## AI Behaviour Rules

- **ALWAYS** load the AI-FACTORY-v2 profile before generating any output
- **ALWAYS** pass output through the security agent before persisting
- **NEVER** expose environment variable values in generated files or logs
- **NEVER** generate code using \`eval()\` or \`new Function()\`
- **NEVER** store or log raw credentials, tokens, or keys
- Output must be **production-ready** — no placeholder text or TODO comments

---

*Generated by AI Copilot Instruction Factory — profile AI-FACTORY-${profileVersion}*
`;
}
